
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package camel.order;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.10
 * Sun Mar 18 12:08:46 CET 2012
 * Generated source version: 2.2.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderEndpointService",
                      portName = "OrderService",
                      targetNamespace = "http://order.camel",
                      wsdlLocation = "file:/Users/chris/Dev/Java/training/camel-cxf/src/main/resources/wsdl/order.wsdl",
                      endpointInterface = "camel.order.OrderEndpoint")
                      
public class OrderEndpointImpl implements OrderEndpoint {

    private static final Logger LOG = Logger.getLogger(OrderEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see camel.order.OrderEndpoint#order(java.lang.String  partName ,)int  amount ,)java.lang.String  customerName )*
     */
    public java.lang.String order(java.lang.String partName,int amount,java.lang.String customerName) { 
        LOG.info("Executing operation order");
        System.out.println(partName);
        System.out.println(amount);
        System.out.println(customerName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
