
/*
 * 
 */

package camel.order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Sun Mar 18 12:08:46 CET 2012
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "OrderEndpointService", 
                  wsdlLocation = "file:/Users/chris/Dev/Java/training/camel-cxf/src/main/resources/wsdl/order.wsdl",
                  targetNamespace = "http://order.camel") 
public class OrderEndpointService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://order.camel", "OrderEndpointService");
    public final static QName OrderService = new QName("http://order.camel", "OrderService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/chris/Dev/Java/training/camel-cxf/src/main/resources/wsdl/order.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/chris/Dev/Java/training/camel-cxf/src/main/resources/wsdl/order.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OrderEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderService")
    public OrderEndpoint getOrderService() {
        return super.getPort(OrderService, OrderEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderService")
    public OrderEndpoint getOrderService(WebServiceFeature... features) {
        return super.getPort(OrderService, OrderEndpoint.class, features);
    }

}
